/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package RedSocial;


import java.awt.Font;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.JTableHeader;



public class Editar extends javax.swing.JPanel {

    /**
     * Creates new form 
     */
    
    Object[][] data;
    Func_usuario adm_usr;
    javax.swing.JInternalFrame parent;

    private javax.swing.JDesktopPane escritorio;
    
    
    public String nombre;
    public String tipo;

    public Editar(Func_usuario adm_usr, javax.swing.JInternalFrame parent, javax.swing.JDesktopPane escritorio, String nombre, String tipo) {
        
        initComponents();
        this.escritorio = escritorio;
        this.parent = parent;
        this.adm_usr = adm_usr;
        
        this.tipo = tipo;
        this.nombre = nombre;
        
        data = null;
        
        JTableHeader th;
        th = tbCoincidencias.getTableHeader();
        th.setFont(new Font("Monospaced", Font.BOLD, 19));
        
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        background = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnDesactivar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbCoincidencias = new javax.swing.JTable();
        jSeparator1 = new javax.swing.JSeparator();
        txtBuscar = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();

        setMinimumSize(new java.awt.Dimension(910, 720));
        setPreferredSize(new java.awt.Dimension(910, 720));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        background.setMinimumSize(new java.awt.Dimension(910, 720));
        background.setPreferredSize(new java.awt.Dimension(910, 720));
        background.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        background.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 30, -1, 59));

        btnDesactivar.setText("Desactivar Cuenta");
        btnDesactivar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDesactivarActionPerformed(evt);
            }
        });
        background.add(btnDesactivar, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 660, 162, 42));

        tbCoincidencias.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        tbCoincidencias.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        tbCoincidencias.setColumnSelectionAllowed(true);
        tbCoincidencias.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        tbCoincidencias.setRowHeight(40);
        tbCoincidencias.setRowMargin(10);
        tbCoincidencias.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbCoincidenciasMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbCoincidencias);
        tbCoincidencias.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);

        background.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, 860, 460));
        background.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 85, 680, -1));

        txtBuscar.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtBuscar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtBuscarKeyReleased(evt);
            }
        });
        background.add(txtBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 41, 622, 31));

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dioses.gif"))); // NOI18N
        jLabel2.setText("jLabel2");
        jLabel2.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        background.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 560, 500, 190));

        add(background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void txtBuscarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBuscarKeyReleased
        // TODO add your handling code here:
        CharSequence c = txtBuscar.getText();

        try {
            data = adm_usr.usrCoincidencias(c, adm_usr.getUser());

            if (!c.isEmpty()) {
                if (data != null) {
                    tbCoincidencias.setModel(new ModelTabla(data));
                } else {
                    Object[][] p = {{"NO HAY COINCIDENCIAS"}};
                    tbCoincidencias.setModel(new ModelTabla(p));
                }

            } else {
                Object[][] p = {{"NO HAY COINCIDENCIAS"}};
                tbCoincidencias.setModel(new ModelTabla(p));
            }

        } catch (IOException ex) {
            Logger.getLogger(Editar.class.getName()).log(Level.SEVERE, null, ex);
        } catch (NoExisteUsr ex) {
            JOptionPane.showMessageDialog(null, "Error " + ex.getMessage(),
                    "Error", JOptionPane.ERROR_MESSAGE);
        }
        
        
    }//GEN-LAST:event_txtBuscarKeyReleased

    private void tbCoincidenciasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbCoincidenciasMouseClicked
        // TODO add your handling code here:
        
        
        
        String usr = String.valueOf(tbCoincidencias.getValueAt(tbCoincidencias.getSelectedRow(), 0));
        
        try {
            new verPerfil(parent,adm_usr, new Func_usuario(usr));
        } catch (IOException ex) {
            JOptionPane.showMessageDialog(null, "Error " + ex.getMessage(),
                    "Error", JOptionPane.ERROR_MESSAGE);
        } catch (NoExisteUsr ex) {
            JOptionPane.showMessageDialog(null, "Error " + ex.getMessage(),
                    "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_tbCoincidenciasMouseClicked

    private void btnDesactivarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDesactivarActionPerformed
        try {
            // TODO add your handling code here:

            int opc = JOptionPane.showConfirmDialog(null, 
                    "Realmente desea descativar esta cuenta?", 
                    "Desactivando cuenta", 
                    JOptionPane.YES_NO_OPTION, 
                    JOptionPane.WARNING_MESSAGE);
            
            if (opc == 0) {
                adm_usr.descUsuario();
                parent.dispose();
                LogIn p = new LogIn(escritorio,nombre, tipo);
                escritorio.add(p);
                p.show();
            }

        } catch (IOException ex) {
            Logger.getLogger(Editar.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnDesactivarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel background;
    private javax.swing.JButton btnDesactivar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable tbCoincidencias;
    private javax.swing.JTextField txtBuscar;
    // End of variables declaration//GEN-END:variables

    
}
