/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package RedSocial;

import java.awt.Color;
import java.awt.Dimension;
import java.awt.LayoutManager;
import javax.swing.ImageIcon;

public class Model_msg extends javax.swing.JPanel {

    private LabelPerfil img_perfil = new LabelPerfil(40);
    
    public Model_msg(ImageIcon image, String msg, String user, String fecha) {
        initComponents();
        
        LayoutManager freed = background.getLayout();
        
        img_perfil.setBounds(15, 25, 40, 40);
        img_perfil.setIcon(image);
        
        img_perfil.setOpaque(false);
        
        
        background.setLayout(null);
        background.add(img_perfil);
        background.setLayout(freed);
        
        lblUser.setText(user);
        txtMsg.setText(msg);
        txtFecha.setText(fecha);
        
    }
    

    public void setearColor(Color c){
        background.setBackground(c);
        txtMsg.setBackground(c);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        background = new javax.swing.JPanel();
        lblUser = new javax.swing.JLabel();
        txtFecha = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtMsg = new javax.swing.JTextArea();
        jSeparator1 = new javax.swing.JSeparator();

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        setMinimumSize(new java.awt.Dimension(880, 125));
        setPreferredSize(new java.awt.Dimension(880, 125));

        background.setMinimumSize(new java.awt.Dimension(880, 125));
        background.setPreferredSize(new java.awt.Dimension(880, 125));

        lblUser.setFont(new java.awt.Font("Lucida Console", 0, 14)); // NOI18N
        lblUser.setText("KelmelLoko");

        txtFecha.setFont(new java.awt.Font("Monospaced", 0, 10)); // NOI18N
        txtFecha.setForeground(new java.awt.Color(171, 71, 188));
        txtFecha.setText("12/04/23      4:00 pm");
        txtFecha.setToolTipText("");

        jScrollPane2.setBorder(null);
        jScrollPane2.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane2.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);
        jScrollPane2.setMinimumSize(new java.awt.Dimension(243, 91));

        txtMsg.setEditable(false);
        txtMsg.setColumns(20);
        txtMsg.setFont(new java.awt.Font("Malgun Gothic", 0, 14)); // NOI18N
        txtMsg.setLineWrap(true);
        txtMsg.setRows(5);
        txtMsg.setText("ajsfdsfjkdsjf;eiwqjfkasdjfasdlkfjasldfjsadklfjeiafjasdklfjewiofjadlkfjsdagjghnvjcasdfasdfasdfasdfsdddddddddddddddddddddddddddddddsafsdafsadddddddddddddddddddfsdfsadfsdaaaaaaaaaaaaaaaaaafsadfsaddddddddddddddd ddfsdfasdf");
        txtMsg.setAutoscrolls(false);
        txtMsg.setBorder(null);
        txtMsg.setFocusable(false);
        txtMsg.setMargin(new java.awt.Insets(10, 10, 10, 10));
        jScrollPane2.setViewportView(txtMsg);

        jSeparator1.setBackground(new java.awt.Color(171, 71, 188));
        jSeparator1.setForeground(new java.awt.Color(98, 56, 118));

        javax.swing.GroupLayout backgroundLayout = new javax.swing.GroupLayout(background);
        background.setLayout(backgroundLayout);
        backgroundLayout.setHorizontalGroup(
            backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(backgroundLayout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addComponent(lblUser, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(txtFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(backgroundLayout.createSequentialGroup()
                .addGap(80, 80, 80)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 730, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(backgroundLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 820, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        backgroundLayout.setVerticalGroup(
            backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(backgroundLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblUser)
                    .addComponent(txtFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(7, 7, 7)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(background, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel background;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JLabel lblUser;
    private javax.swing.JLabel txtFecha;
    private javax.swing.JTextArea txtMsg;
    // End of variables declaration//GEN-END:variables
}
