/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package RedSocial;

import java.awt.Color;
import java.awt.Dimension;
import java.awt.FlowLayout;
import java.awt.GradientPaint;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.Image;
import java.awt.Rectangle;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.io.InputStream;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.imageio.stream.ImageInputStream;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JScrollBar;
import javax.swing.Timer;


public class TimeLine extends javax.swing.JPanel {

    /**
     * Creates new form TimeLine
     */
    
    private Func_usuario adm_usr;
    private ArrayList<String[]> twits;
    
    private Color color1 = new Color(50,26,71);
    private Color color2 = new Color(116,62,172);
    
    
    public TimeLine(Func_usuario adm_usr) throws IOException, FileNotFoundException, NoExisteUsr {
        
        initComponents();
        
        this.adm_usr = adm_usr;
        this.twits = adm_usr.cargarTwits();
        
        cargarTwits();
        
        

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToggleButton1 = new javax.swing.JToggleButton();
        background = new javax.swing.JPanel();
        content_scroll = new javax.swing.JScrollPane();
        content = new javax.swing.JPanel();
        txtMensj = new javax.swing.JTextField();
        btnSubir = new javax.swing.JButton();

        jToggleButton1.setText("jToggleButton1");

        setMinimumSize(new java.awt.Dimension(910, 720));
        setPreferredSize(new java.awt.Dimension(910, 720));

        background.setMinimumSize(new java.awt.Dimension(910, 720));
        background.setPreferredSize(new java.awt.Dimension(910, 720));

        content_scroll.setBorder(null);
        content_scroll.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        content_scroll.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);
        content_scroll.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        content_scroll.setMinimumSize(new java.awt.Dimension(0, 0));
        content_scroll.setPreferredSize(new java.awt.Dimension(880, 713));
        content_scroll.setRequestFocusEnabled(false);

        content.setAutoscrolls(true);
        content.setMaximumSize(new java.awt.Dimension(880, 32767));
        content.setMinimumSize(new java.awt.Dimension(880, 0));
        content.setName(""); // NOI18N
        content.setPreferredSize(new java.awt.Dimension(880, 0));

        javax.swing.GroupLayout contentLayout = new javax.swing.GroupLayout(content);
        content.setLayout(contentLayout);
        contentLayout.setHorizontalGroup(
            contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 880, Short.MAX_VALUE)
        );
        contentLayout.setVerticalGroup(
            contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 626, Short.MAX_VALUE)
        );

        content_scroll.setViewportView(content);

        txtMensj.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtMensj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMensjActionPerformed(evt);
            }
        });
        txtMensj.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtMensjKeyPressed(evt);
            }
        });

        btnSubir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon_enviar.png"))); // NOI18N
        btnSubir.setFocusable(false);
        btnSubir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout backgroundLayout = new javax.swing.GroupLayout(background);
        background.setLayout(backgroundLayout);
        backgroundLayout.setHorizontalGroup(
            backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(backgroundLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(txtMensj, javax.swing.GroupLayout.PREFERRED_SIZE, 805, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(btnSubir, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 31, Short.MAX_VALUE))
            .addGroup(backgroundLayout.createSequentialGroup()
                .addComponent(content_scroll, javax.swing.GroupLayout.PREFERRED_SIZE, 880, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        backgroundLayout.setVerticalGroup(
            backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(backgroundLayout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addComponent(content_scroll, javax.swing.GroupLayout.PREFERRED_SIZE, 626, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(backgroundLayout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(txtMensj, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnSubir, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents

    
    private void txtMensjActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMensjActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMensjActionPerformed

    private void btnSubirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubirActionPerformed

        // TODO add your handling code here:
        String msg = txtMensj.getText();

        if (msg.length() > 0) {
            try {
                adm_usr.guardarTwit(msg);

                txtMensj.setText("");

                cargarTwits();
                this.revalidate();
                this.repaint();
                JScrollBar barra = content_scroll.getVerticalScrollBar();
                barra.setValue(barra.getMaximum());

            } catch (IOException ex) {
                JOptionPane.showMessageDialog(null, "Error: " + ex.getMessage());
            } catch (NoExisteUsr ex) {
                JOptionPane.showMessageDialog(null, "Error " + ex.getMessage(),
                        "Error", JOptionPane.ERROR_MESSAGE);

            }

        }
    }//GEN-LAST:event_btnSubirActionPerformed

    private void txtMensjKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtMensjKeyPressed
        // TODO add your handling code here:
        
        String msg = txtMensj.getText();
        
        if(msg.length() > 140){
             JOptionPane.showMessageDialog(null,
                    "EYYY, el twit sobrepasa los 140 caracteres\nreduzcalo", "Twit muy grande",
                    JOptionPane.WARNING_MESSAGE);
             
             msg = msg.substring(0,141);
             
             txtMensj.setText(msg);
        }
    }//GEN-LAST:event_txtMensjKeyPressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel background;
    private javax.swing.JButton btnSubir;
    private javax.swing.JPanel content;
    private javax.swing.JScrollPane content_scroll;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JTextField txtMensj;
    // End of variables declaration//GEN-END:variables

    private void cargarTwits() throws IOException, FileNotFoundException, NoExisteUsr {

        
        
        content.removeAll();
        
        content.setLayout(new FlowLayout(FlowLayout.LEADING,0,0));
        
        
        
        twits = adm_usr.cargarTwits();
        
        if (!twits.isEmpty()) {

            Model_msg[] twits_p = new Model_msg[twits.size()];

            for (int i = 0; i < twits_p.length; i++) {

                String[] mensaje = twits.get(i);

                Func_usuario tmp = new Func_usuario(mensaje[0]);

                //formato de fecha
                Calendar fecha = Calendar.getInstance();
                fecha.setTimeInMillis(Long.parseLong(mensaje[2]));

                String fecha_f = String.format("%d/%d/%d       %d:%02d %s", fecha.get(Calendar.DATE),
                        fecha.get(Calendar.MONTH), fecha.get(Calendar.YEAR), fecha.get(Calendar.HOUR),
                        fecha.get(Calendar.MINUTE), ((fecha.get(Calendar.AM_PM) == 0) ? "am" : "pm"));

                BufferedImage newImage = new BufferedImage(
                        tmp.getImg_perfil().getWidth(null),
                        tmp.getImg_perfil().getHeight(null),
                        BufferedImage.TYPE_INT_ARGB);

                Graphics2D graphics = newImage.createGraphics();
                graphics.drawImage(tmp.getImg_perfil(), 0, 0, null);
                graphics.dispose();

                Image img = newImage.getScaledInstance(40, 40, Image.SCALE_DEFAULT);

                twits_p[i] = new Model_msg(new ImageIcon(img), mensaje[1],
                        tmp.getUser(), fecha_f);

                content.setPreferredSize(new Dimension(1040, (i + 1) * 125));

                content.add(twits_p[i]);

                content.revalidate();
                content.repaint();

                content_scroll.revalidate();
                content_scroll.repaint();
                
                JScrollBar barra = content_scroll.getVerticalScrollBar();
                barra.setValue(barra.getMaximum());
                content_scroll.repaint();
                
                this.repaint();
            }

        } else {
            ImageIcon vacio_icon = new ImageIcon("varios/icon_vacio.png");

            Model_msg a = new Model_msg(vacio_icon, "No tienes ni un twit\n  Sigue a otros para visualizar sus twits :> e interectuar) ", "", "");
            content.add(a);
        }

        desplazarScroll();

        background.revalidate();
        background.repaint();

    }

    private void desplazarScroll() {

        JScrollBar barra = content_scroll.getVerticalScrollBar();
        barra.setValue(barra.getMaximum());
    }
    
    
}
