/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package RedSocial;

import java.awt.Dimension;
import java.awt.FlowLayout;
import java.awt.Graphics2D;
import java.awt.Image;
import java.awt.image.BufferedImage;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JScrollBar;


public class verTwits extends javax.swing.JDialog {

    /**
     * Creates new form verTwits
     */
    
    
    private ArrayList<String[]> twits;
    private Func_usuario adm_usr;
    
    public verTwits(java.awt.Dialog parent, boolean modal, Func_usuario adm_usr) throws IOException {
        super(parent, modal);
        initComponents();
        
        this.adm_usr = adm_usr;
        this.setLocationRelativeTo(parent);
        this.txtUsuario.setText("Twits de " + adm_usr.getUser());
        
        
        try {
            cargarTwits();
            this.revalidate();
            this.repaint();
        } catch (FileNotFoundException | NoExisteUsr ex) {
            JOptionPane.showMessageDialog(null, "Error " + ex.getMessage(),
                    "Error", JOptionPane.ERROR_MESSAGE);

        }
        
    }
    
    
    
    private void cargarTwits() throws IOException, FileNotFoundException, NoExisteUsr {

        
        
        content.removeAll();
        
        content.setLayout(new FlowLayout(FlowLayout.LEADING,0,0));
        
        
        
        twits = adm_usr.misTwits();
        
        if (!twits.isEmpty()) {

            Model_msg[] twits_p = new Model_msg[twits.size()];

            for (int i = 0; i < twits_p.length; i++) {

                String[] mensaje = twits.get(i);

                Func_usuario tmp = new Func_usuario(mensaje[0]);

                //formato de fecha
                Calendar fecha = Calendar.getInstance();
                fecha.setTimeInMillis(Long.parseLong(mensaje[2]));

                String fecha_f = String.format("%d/%d/%d       %d:%02d %s", fecha.get(Calendar.DATE),
                        fecha.get(Calendar.MONTH), fecha.get(Calendar.YEAR), fecha.get(Calendar.HOUR),
                        fecha.get(Calendar.MINUTE), ((fecha.get(Calendar.AM_PM) == 0) ? "am" : "pm"));

                BufferedImage newImage = new BufferedImage(
                        tmp.getImg_perfil().getWidth(null),
                        tmp.getImg_perfil().getHeight(null),
                        BufferedImage.TYPE_INT_ARGB);

                Graphics2D graphics = newImage.createGraphics();
                graphics.drawImage(tmp.getImg_perfil(), 0, 0, null);
                graphics.dispose();

                Image img = newImage.getScaledInstance(40, 40, Image.SCALE_DEFAULT);

                twits_p[i] = new Model_msg(new ImageIcon(img), mensaje[1],
                        tmp.getUser(), fecha_f);

                content.setPreferredSize(new Dimension(1040, (i + 1) * 125));

                content.add(twits_p[i]);

                content.revalidate();
                content.repaint();

                content_scroll.revalidate();
                content_scroll.repaint();
                
                JScrollBar barra = content_scroll.getVerticalScrollBar();
                barra.setValue(barra.getMaximum());
                content_scroll.repaint();
                
                this.repaint();
            }

        } else {
            ImageIcon vacio_icon = new ImageIcon("varios/icon_vacio.png");

            Model_msg a = new Model_msg(vacio_icon, "No tienes ni un twit\n  Sigue a otros para visualizar sus twits :> e interectuar) ", "", "");
            content.add(a);
        }

    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtUsuario = new javax.swing.JLabel();
        content_scroll = new javax.swing.JScrollPane();
        content = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        txtUsuario.setFont(new java.awt.Font("Monospaced", 0, 18)); // NOI18N
        txtUsuario.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtUsuario.setText("twite");

        content_scroll.setBorder(null);
        content_scroll.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        content_scroll.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);
        content_scroll.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        content_scroll.setMinimumSize(new java.awt.Dimension(1041, 713));
        content_scroll.setPreferredSize(new java.awt.Dimension(1040, 713));
        content_scroll.setRequestFocusEnabled(false);

        content.setAutoscrolls(true);
        content.setMinimumSize(new java.awt.Dimension(880, 0));
        content.setName(""); // NOI18N
        content.setPreferredSize(new java.awt.Dimension(880, 740));

        javax.swing.GroupLayout contentLayout = new javax.swing.GroupLayout(content);
        content.setLayout(contentLayout);
        contentLayout.setHorizontalGroup(
            contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 880, Short.MAX_VALUE)
        );
        contentLayout.setVerticalGroup(
            contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 740, Short.MAX_VALUE)
        );

        content_scroll.setViewportView(content);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(txtUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(content_scroll, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addComponent(txtUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(content_scroll, javax.swing.GroupLayout.PREFERRED_SIZE, 650, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel content;
    private javax.swing.JScrollPane content_scroll;
    private javax.swing.JLabel txtUsuario;
    // End of variables declaration//GEN-END:variables
}
