/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package linux;



import Usuarios.CrearcionUsuarios;

import java.awt.Color;
import java.awt.Container;
import java.awt.Event;
import java.awt.PopupMenu;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.net.URL;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.BoxLayout;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JDialog;
import javax.swing.JFrame;
import javax.swing.JInternalFrame;
import javax.swing.JList;
import javax.swing.JMenuItem;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JPopupMenu;
import javax.swing.JScrollPane;
import javax.swing.Timer;
import player.Spotify;
import visorimagenes.Imagenes;
import visorimagenes.Visor;
import Usuarios.SistemaArchivos;

/**
 *
 * @author aleja
 */
public class Inicio extends javax.swing.JFrame {
    private FileManager fileManagerInstance;
     
      visorimagenes.Visor casa;
      JPopupMenu popupMenuUser = new JPopupMenu();
      JPopupMenu popupMenuoff = new JPopupMenu();
       CrearcionUsuarios CU = new CrearcionUsuarios();
       public static String nombreIngresado;
       public static String tipoIngresado;
       public static String typoIngresado;
       Login log;


    /**
     * Creates new form 
     */
    public Inicio() {
        initComponents();

        
        JMenuItem CreateUser = new JMenuItem("Crear Usuario");
        
        
        popupMenuUser.add(CreateUser);
        
        popupMenuUser.setBackground(Color.GRAY);
        
        JMenuItem off = new JMenuItem("Apagar");
        JMenuItem cerrarsesion = new JMenuItem("Cerrar Sesion");
        
        
        
        popupMenuoff.add(off);
        popupMenuoff.add(cerrarsesion);     
        popupMenuoff.setBackground(Color.GRAY);
  
        paneldeapps.setVisible(false);
        
               
        casa = new Visor();       
        timer.start(); 
        
        CreateUser.addActionListener(new ActionListener() {
          @Override
          public void actionPerformed(ActionEvent e) {
              
             
                
               
            if (log.UserLoging != null && log.UserLoging.equals("admin")) {
           
            Usuarios.CrearcionUsuarios cre = new CrearcionUsuarios();
            pantalladeinicio.add(cre).setVisible(true);
            paneldeapps.setVisible(false);
            System.out.println("name" + log.UserLoging);
        } else {
           
            JOptionPane.showMessageDialog(null, "No tienes permisos para crear usuarios.", "Error", JOptionPane.ERROR_MESSAGE);
        }
                

                
            }
        });
        
        off.addActionListener(new ActionListener() {
          @Override
          public void actionPerformed(ActionEvent e) {
                System.exit(0);
            }
        });
        
        cerrarsesion.addActionListener(new ActionListener() {
          @Override
          public void actionPerformed(ActionEvent e) {
                 Login uwuntu = new Login();
                 uwuntu.setVisible(true);
                 dispose();
            }
        });


    }
    
    Timer timer = new Timer(1000, new ActionListener() {
    @Override
    public void actionPerformed(ActionEvent e) {
        // Código que se ejecutará cada segundo
        Date fechaActual = new Date();
        SimpleDateFormat formato = new SimpleDateFormat("dd/MM/yyyy\n HH:mm:ss");
        String fechaFormateada = formato.format(fechaActual);
    
    }
});
    
    
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu1 = new javax.swing.JMenu();
        jPanel2 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        pantalladeinicio = new javax.swing.JDesktopPane();
        paneldeapps = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        Menuinico = new javax.swing.JPanel();
        Itunes = new javax.swing.JButton();
        Itunes1 = new javax.swing.JButton();
        Itunes2 = new javax.swing.JButton();
        Itunes3 = new javax.swing.JButton();
        Callculadora = new javax.swing.JButton();
        Itunes5 = new javax.swing.JButton();
        Itunes4 = new javax.swing.JButton();
        Itunes6 = new javax.swing.JButton();
        Itunes7 = new javax.swing.JButton();
        Itunes8 = new javax.swing.JButton();
        Callculadora1 = new javax.swing.JButton();
        Itunes9 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();

        jMenu1.setText("jMenu1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(204, 204, 204));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/win.png"))); // NOI18N
        jButton1.setBorderPainted(false);
        jButton1.setContentAreaFilled(false);
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/Fexplorar.png"))); // NOI18N
        jButton2.setBorderPainted(false);
        jButton2.setContentAreaFilled(false);
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/Calculadora.png"))); // NOI18N
        jButton3.setBorderPainted(false);
        jButton3.setContentAreaFilled(false);
        jButton3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton3MouseClicked(evt);
            }
        });
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(544, 544, 544)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(824, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(9, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 760, 1530, 50));

        pantalladeinicio.setBackground(new java.awt.Color(0, 102, 204));
        pantalladeinicio.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pantalladeinicioMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pantalladeinicioMouseEntered(evt);
            }
        });

        paneldeapps.setBackground(new java.awt.Color(102, 102, 102));
        paneldeapps.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                paneldeappsMouseExited(evt);
            }
        });
        paneldeapps.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Menuinico.setBackground(new java.awt.Color(153, 153, 153));
        Menuinico.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                MenuinicoMouseExited(evt);
            }
        });

        Itunes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/ITunes_logo.png"))); // NOI18N
        Itunes.setText("Itunes");
        Itunes.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        Itunes.setBorderPainted(false);
        Itunes.setContentAreaFilled(false);
        Itunes.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        Itunes.setMaximumSize(new java.awt.Dimension(521, 451));
        Itunes.setMinimumSize(new java.awt.Dimension(521, 451));
        Itunes.setPreferredSize(new java.awt.Dimension(21, 51));
        Itunes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ItunesActionPerformed(evt);
            }
        });

        Itunes1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/Word3.png"))); // NOI18N
        Itunes1.setText("Word");
        Itunes1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        Itunes1.setBorderPainted(false);
        Itunes1.setContentAreaFilled(false);
        Itunes1.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        Itunes1.setMaximumSize(new java.awt.Dimension(521, 451));
        Itunes1.setMinimumSize(new java.awt.Dimension(521, 451));
        Itunes1.setPreferredSize(new java.awt.Dimension(21, 51));
        Itunes1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Itunes1ActionPerformed(evt);
            }
        });

        Itunes2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/photo.png"))); // NOI18N
        Itunes2.setText("Photos");
        Itunes2.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        Itunes2.setBorderPainted(false);
        Itunes2.setContentAreaFilled(false);
        Itunes2.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        Itunes2.setMaximumSize(new java.awt.Dimension(521, 451));
        Itunes2.setMinimumSize(new java.awt.Dimension(521, 451));
        Itunes2.setPreferredSize(new java.awt.Dimension(21, 51));
        Itunes2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Itunes2ActionPerformed(evt);
            }
        });

        Itunes3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/CMD.png"))); // NOI18N
        Itunes3.setText("Cmd");
        Itunes3.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        Itunes3.setBorderPainted(false);
        Itunes3.setContentAreaFilled(false);
        Itunes3.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        Itunes3.setMaximumSize(new java.awt.Dimension(521, 451));
        Itunes3.setMinimumSize(new java.awt.Dimension(521, 451));
        Itunes3.setPreferredSize(new java.awt.Dimension(21, 51));
        Itunes3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Itunes3ActionPerformed(evt);
            }
        });

        Callculadora.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/Calculadora.png"))); // NOI18N
        Callculadora.setText("Calculadora");
        Callculadora.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        Callculadora.setBorderPainted(false);
        Callculadora.setContentAreaFilled(false);
        Callculadora.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        Callculadora.setMaximumSize(new java.awt.Dimension(521, 451));
        Callculadora.setMinimumSize(new java.awt.Dimension(521, 451));
        Callculadora.setPreferredSize(new java.awt.Dimension(21, 51));
        Callculadora.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CallculadoraActionPerformed(evt);
            }
        });

        Itunes5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/Fexplorar.png"))); // NOI18N
        Itunes5.setText("Explorer");
        Itunes5.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        Itunes5.setBorderPainted(false);
        Itunes5.setContentAreaFilled(false);
        Itunes5.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        Itunes5.setMaximumSize(new java.awt.Dimension(521, 451));
        Itunes5.setMinimumSize(new java.awt.Dimension(521, 451));
        Itunes5.setPreferredSize(new java.awt.Dimension(21, 51));
        Itunes5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Itunes5ActionPerformed(evt);
            }
        });

        Itunes4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/crome.png"))); // NOI18N
        Itunes4.setText("Chrome");
        Itunes4.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        Itunes4.setBorderPainted(false);
        Itunes4.setContentAreaFilled(false);
        Itunes4.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        Itunes4.setMaximumSize(new java.awt.Dimension(521, 451));
        Itunes4.setMinimumSize(new java.awt.Dimension(521, 451));
        Itunes4.setPreferredSize(new java.awt.Dimension(21, 51));
        Itunes4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Itunes4ActionPerformed(evt);
            }
        });

        Itunes6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/neatbeans.png"))); // NOI18N
        Itunes6.setText("NeatBeans");
        Itunes6.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        Itunes6.setBorderPainted(false);
        Itunes6.setContentAreaFilled(false);
        Itunes6.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        Itunes6.setMaximumSize(new java.awt.Dimension(521, 451));
        Itunes6.setMinimumSize(new java.awt.Dimension(521, 451));
        Itunes6.setPreferredSize(new java.awt.Dimension(21, 51));
        Itunes6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Itunes6ActionPerformed(evt);
            }
        });

        Itunes7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/pngwing.com (2) (1).png"))); // NOI18N
        Itunes7.setText("Overwatch");
        Itunes7.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        Itunes7.setBorderPainted(false);
        Itunes7.setContentAreaFilled(false);
        Itunes7.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        Itunes7.setMaximumSize(new java.awt.Dimension(521, 451));
        Itunes7.setMinimumSize(new java.awt.Dimension(521, 451));
        Itunes7.setPreferredSize(new java.awt.Dimension(21, 51));
        Itunes7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Itunes7ActionPerformed(evt);
            }
        });

        Itunes8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/pngwing.com (1).png"))); // NOI18N
        Itunes8.setText("VLCplay");
        Itunes8.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        Itunes8.setBorderPainted(false);
        Itunes8.setContentAreaFilled(false);
        Itunes8.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        Itunes8.setMaximumSize(new java.awt.Dimension(521, 451));
        Itunes8.setMinimumSize(new java.awt.Dimension(521, 451));
        Itunes8.setPreferredSize(new java.awt.Dimension(21, 51));
        Itunes8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Itunes8ActionPerformed(evt);
            }
        });

        Callculadora1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/epic.png"))); // NOI18N
        Callculadora1.setText("Epic Game");
        Callculadora1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        Callculadora1.setBorderPainted(false);
        Callculadora1.setContentAreaFilled(false);
        Callculadora1.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        Callculadora1.setMaximumSize(new java.awt.Dimension(521, 451));
        Callculadora1.setMinimumSize(new java.awt.Dimension(521, 451));
        Callculadora1.setPreferredSize(new java.awt.Dimension(21, 51));
        Callculadora1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Callculadora1ActionPerformed(evt);
            }
        });

        Itunes9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/twitter.png"))); // NOI18N
        Itunes9.setText("Twitter");
        Itunes9.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        Itunes9.setBorderPainted(false);
        Itunes9.setContentAreaFilled(false);
        Itunes9.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        Itunes9.setMaximumSize(new java.awt.Dimension(521, 451));
        Itunes9.setMinimumSize(new java.awt.Dimension(521, 451));
        Itunes9.setPreferredSize(new java.awt.Dimension(21, 51));
        Itunes9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Itunes9ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout MenuinicoLayout = new javax.swing.GroupLayout(Menuinico);
        Menuinico.setLayout(MenuinicoLayout);
        MenuinicoLayout.setHorizontalGroup(
            MenuinicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MenuinicoLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(MenuinicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(MenuinicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(MenuinicoLayout.createSequentialGroup()
                            .addComponent(Itunes7, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(Itunes6, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(Itunes4, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(MenuinicoLayout.createSequentialGroup()
                            .addComponent(Itunes8, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(Callculadora1, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(Itunes9, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(MenuinicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(MenuinicoLayout.createSequentialGroup()
                            .addComponent(Itunes1, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(Itunes2, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(Itunes3, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(MenuinicoLayout.createSequentialGroup()
                            .addComponent(Itunes, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(Callculadora, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(Itunes5, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(66, Short.MAX_VALUE))
        );
        MenuinicoLayout.setVerticalGroup(
            MenuinicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MenuinicoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(MenuinicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Itunes, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Callculadora, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Itunes5, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(MenuinicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Itunes1, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Itunes2, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Itunes3, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(MenuinicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Callculadora1, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Itunes9, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Itunes8, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(MenuinicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Itunes7, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Itunes6, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Itunes4, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(498, Short.MAX_VALUE))
        );

        jScrollPane2.setViewportView(Menuinico);

        paneldeapps.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 450, 580));

        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/user.png"))); // NOI18N
        jButton4.setText("User");
        jButton4.setBorderPainted(false);
        jButton4.setContentAreaFilled(false);
        jButton4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton4MouseClicked(evt);
            }
        });
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        paneldeapps.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 110, 40));

        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/turn.png"))); // NOI18N
        jButton5.setBorderPainted(false);
        jButton5.setContentAreaFilled(false);
        jButton5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton5MouseClicked(evt);
            }
        });
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        paneldeapps.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 10, 40, 40));

        pantalladeinicio.setLayer(paneldeapps, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout pantalladeinicioLayout = new javax.swing.GroupLayout(pantalladeinicio);
        pantalladeinicio.setLayout(pantalladeinicioLayout);
        pantalladeinicioLayout.setHorizontalGroup(
            pantalladeinicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pantalladeinicioLayout.createSequentialGroup()
                .addGap(386, 386, 386)
                .addComponent(paneldeapps, javax.swing.GroupLayout.PREFERRED_SIZE, 446, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(698, Short.MAX_VALUE))
        );
        pantalladeinicioLayout.setVerticalGroup(
            pantalladeinicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pantalladeinicioLayout.createSequentialGroup()
                .addGap(0, 374, Short.MAX_VALUE)
                .addComponent(paneldeapps, javax.swing.GroupLayout.PREFERRED_SIZE, 386, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        getContentPane().add(pantalladeinicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1530, 760));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void paneldeappsMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_paneldeappsMouseExited
        // TODO add your handling code here:
       

    }//GEN-LAST:event_paneldeappsMouseExited

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        // TODO add your handling code here:
                paneldeapps.setVisible(true);

    }//GEN-LAST:event_jButton1MouseClicked

    private void ItunesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ItunesActionPerformed
        // TODO add your handling code here:
//        player.PlayerMemo itunes = new PlayerMemo();
        player.Spotify itunes = new Spotify();
        itunes.setVisible(true);
        itunes.toFront();
        pantalladeinicio.add(itunes);
               
                paneldeapps.setVisible(false);

    

    }//GEN-LAST:event_ItunesActionPerformed

    private void Itunes1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Itunes1ActionPerformed
        // TODO add your handling code here:
//        texteditor.Principal2 word = new texteditor.Principal2();
//
//        jDesktopPane1.add(word).setVisible(true);
//                paneldeapps.setVisible(false);
                
       texteditor.texteditor word = new texteditor.texteditor();


        pantalladeinicio.add(word).setVisible(true);
                paneldeapps.setVisible(false);

    }//GEN-LAST:event_Itunes1ActionPerformed

    private void Itunes2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Itunes2ActionPerformed
        // TODO add your handling code here:
//        visorimagenes.Visor photo = new  visorimagenes.Visor();
        visorimagenes.Imagenes photo = new Imagenes();
//        photo.setVisible(true);
        pantalladeinicio.add(photo).setVisible(true);
        paneldeapps.setVisible(false);
                
                

    }//GEN-LAST:event_Itunes2ActionPerformed

    private void Itunes3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Itunes3ActionPerformed
        // TODO add your handling code here:
        cmd.CommandConsol cmd = new cmd.CommandConsol();
//        cmd.setVisible(true);


    // Add the internal frame to the desktop pane
    pantalladeinicio.add(cmd).setVisible(true);
    
    // Hide the paneldeapps or perform any other necessary actions
    paneldeapps.setVisible(false);

    }//GEN-LAST:event_Itunes3ActionPerformed

    private void CallculadoraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CallculadoraActionPerformed
        // TODO add your handling code here:
        try {
            Runtime objet = Runtime.getRuntime();
            objet.exec("C:/Windows/System32/calc.exe");
                    paneldeapps.setVisible(false);

        } catch (Exception e) {
        }
    }//GEN-LAST:event_CallculadoraActionPerformed

    private void Itunes5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Itunes5ActionPerformed
        // TODO add your handling code here:
        fileManagerInstance = new FileManager();
        JInternalFrame fileManagerFrame = new JInternalFrame("Internal Frame", true, true, true, true);
        paneldeapps.setVisible(false);
                fileManagerFrame.setContentPane(fileManagerInstance.getGui());
                fileManagerFrame.pack();
                fileManagerFrame.setVisible(true);
            
           pantalladeinicio.add(fileManagerFrame).setVisible(true);
                
                
          
        
    }//GEN-LAST:event_Itunes5ActionPerformed

    private void Itunes4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Itunes4ActionPerformed
        // TODO add your handling code here:
        
         try {
            Runtime objet = Runtime.getRuntime();
            objet.exec("C:/Program Files/Google/Chrome/Application/chrome.exe");
                    paneldeapps.setVisible(false);

        } catch (Exception e) {
        }
        
    }//GEN-LAST:event_Itunes4ActionPerformed

    private void Itunes6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Itunes6ActionPerformed
        // TODO add your handling code here:
        System.out.println("usuario:"+nombreIngresado);
        System.out.println("tipo:"+typoIngresado);
                paneldeapps.setVisible(false);

            JOptionPane.showMessageDialog(null, "Error: Aplicacion en Uso", "Error", JOptionPane.ERROR_MESSAGE);

        
    }//GEN-LAST:event_Itunes6ActionPerformed

    private void Itunes7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Itunes7ActionPerformed
        // TODO add your handling code here:
        
        try {
            Runtime objet = Runtime.getRuntime();
            objet.exec("C:/games/Overwatch/Overwatch Launcher.exe"); 
                    paneldeapps.setVisible(false);

        } catch (Exception e) {
             System.out.println("no se puede");
        }
    }//GEN-LAST:event_Itunes7ActionPerformed

    private void Itunes8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Itunes8ActionPerformed
        // TODO add your handling code here:
//        player.Spotify itunes = new Spotify();
//        itunes.setVisible(true);
//        itunes.toFront();
//        pantalladeinicio.add(itunes);
//               
//                paneldeapps.setVisible(false);
            JOptionPane.showMessageDialog(null, "Error: Aplicacion No instalada", "Error", JOptionPane.ERROR_MESSAGE);


    }//GEN-LAST:event_Itunes8ActionPerformed

    private void Callculadora1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Callculadora1ActionPerformed
        // TODO add your handling code here:
          
          try {
            
            Runtime objet = Runtime.getRuntime();
            objet.exec("C:/Program Files (x86)/Epic Games/Launcher/Portal/Binaries/Win32/EpicGamesLauncher.exe"); 
                    paneldeapps.setVisible(false);

            
        } catch (Exception e) {
             System.out.println("no se puede");
        }
    }//GEN-LAST:event_Callculadora1ActionPerformed

    private void Itunes9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Itunes9ActionPerformed
        // TODO add your handling code here:
        Twitter.Login word = new Twitter.Login();
        word.setVisible(true);
//        setInternalFrameCenterLocation(word);
//       pantalladeinicio.add(word).setVisible(true);
//        word.setVisible(true);
                paneldeapps.setVisible(false);
        
    }//GEN-LAST:event_Itunes9ActionPerformed

    private void MenuinicoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MenuinicoMouseExited
        // TODO add your handling code here:
//         paneldeapps.setVisible(false);
    }//GEN-LAST:event_MenuinicoMouseExited

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jButton2MouseClicked

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        
        
        
         fileManagerInstance = new FileManager();
        JInternalFrame fileManagerFrame = new JInternalFrame("Internal Frame", true, true, true, true);
        paneldeapps.setVisible(false);
                fileManagerFrame.setContentPane(fileManagerInstance.getGui());
                fileManagerFrame.pack();
                fileManagerFrame.setVisible(true);
            
           pantalladeinicio.add(fileManagerFrame).setVisible(true);
                

          
       
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton3MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3MouseClicked

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
          try {
            Runtime objet = Runtime.getRuntime();
            objet.exec("C:/Windows/System32/calc.exe");
            
        } catch (Exception e) {
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
//         JPanel panel = new JPanel();
////        PopupMenu botonMostrarDialogo;
////            this.add(mostrarCuadroDialogo);
//
//            
//         mostrarDialogo(this);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
//        popupMenuoff.setVisible(true);
//        popupMenuoff.show(evt.getComponent(), evt.getX(), evt.getY());
       
    }//GEN-LAST:event_jButton5ActionPerformed

    private void pantalladeinicioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pantalladeinicioMouseClicked
        // TODO add your handling code here:
         paneldeapps.setVisible(false);
      
    }//GEN-LAST:event_pantalladeinicioMouseClicked

    private void jButton4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton4MouseClicked
        // TODO add your handling code here:
        
        popupMenuUser.setVisible(true);
        popupMenuUser.show(evt.getComponent(), evt.getX(), evt.getY());
        
    }//GEN-LAST:event_jButton4MouseClicked

    private void jButton5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton5MouseClicked
        // TODO add your handling code here:
        popupMenuoff.setVisible(true);
        popupMenuoff.show(evt.getComponent(), evt.getX(), evt.getY());
    }//GEN-LAST:event_jButton5MouseClicked

    private void pantalladeinicioMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pantalladeinicioMouseEntered
        // TODO add your handling code here:
                 

    }//GEN-LAST:event_pantalladeinicioMouseEntered

  
   
   
    
   /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Inicio().setVisible(true);
            }
        });
    }
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Callculadora;
    private javax.swing.JButton Callculadora1;
    private javax.swing.JButton Itunes;
    private javax.swing.JButton Itunes1;
    private javax.swing.JButton Itunes2;
    private javax.swing.JButton Itunes3;
    private javax.swing.JButton Itunes4;
    private javax.swing.JButton Itunes5;
    private javax.swing.JButton Itunes6;
    private javax.swing.JButton Itunes7;
    private javax.swing.JButton Itunes8;
    private javax.swing.JButton Itunes9;
    private javax.swing.JPanel Menuinico;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JPanel paneldeapps;
    public static javax.swing.JDesktopPane pantalladeinicio;
    // End of variables declaration//GEN-END:variables
}
